freebsd_instance:
  image_family: freebsd-13-0

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  install_script: pkg install -y go
  get_script: go get ./...
  build_script: go build ./...
  test_script: go test ./...
