language: go
go:
- "1.10.x"
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - master
  - develop
install:
  - env GO111MODULE=on go get github.com/intel/tfortools
